### ISSUE TITLE
Tirar a pesquisa no campo ab (resumo)

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/BVS-InfoButton#57]
Ao traduzir os parâmetros da pesquisa infobutton em pesquisa IAHx, retirar a pesquisa no campo "ab" (resumo). Pesquisar em "mh" e "ti".

**Comment by renatomurasaki** [comment]
Utilizar "ab" somente se "mh" retornar zero documentos.


________________________________
De: Heitor Barbieri <notifications@github.com>
Enviado: quarta-feira, 20 de março de 2019 12:50
Para: bireme/BVS-InfoButton
Cc: Subscribed
Assunto: [bireme/BVS-InfoButton] Tirar a pesquisa no campo ab (resumo) (#57)


Ao traduzir os parâmetros da pesquisa infobutton em pesquisa IAHx, retirar a pesquisa no campo "ab" (resumo). Pesquisar em "mh" e "ti".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2FBVS-InfoButton%2Fissues%2F57&data=02%7C01%7Cmurasaki%40paho.org%7Cdfd1c8b1c16940cba9f608d6ad4bd474%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636886938539932937&sdata=ujgsm1x5tRW5UzlxpwBGs7OLGvv0Rso2kuFdANcGuyc%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABK16mJ7nVpEFQVxSQ5uJps83ALgot6fks5vYljXgaJpZM4b_pLA&data=02%7C01%7Cmurasaki%40paho.org%7Cdfd1c8b1c16940cba9f608d6ad4bd474%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636886938539942950&sdata=A2TP93MkRj52vBrSIkuPXmpn6d33cZmol4r8OkwhUBM%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
