### ISSUE TITLE
Acrescentar os idiomas Português e Espanhol do CID-10 e Snomed no índice de busca

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/BVS-InfoButton#58]
Quando não se encontra a conversão do código de um thesaurus no DeCS, utiliza-se o texto descritivo associado ao descritor como parâmetro de busca. Atualmente este texto descritivo está apenas em inglês. Acrescentar o mesmo em português e espanhol.

**Comment by renatomurasaki** [comment]
Incluir os idiomas portugues e espanhol no cenário em que há conversão com DeCS, ao construir a expressão "ti" e "ab".


________________________________
De: Heitor Barbieri <notifications@github.com>
Enviado: quarta-feira, 20 de março de 2019 12:53
Para: bireme/BVS-InfoButton
Cc: Subscribed
Assunto: [bireme/BVS-InfoButton] Acrescentar os idiomas Português e Espanhol do CID-10 e Snomed no índice de busca (#58)


Quando não se encontra a conversão do código de um thesaurus no DeCS, utiliza-se o texto descritivo associado ao descritor como parâmetro de busca. Atualmente este texto descritivo está apenas em inglês. Acrescentar o mesmo em português e espanhol.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2FBVS-InfoButton%2Fissues%2F58&data=02%7C01%7Cmurasaki%40paho.org%7Ce82732dc7ae54911719c08d6ad4c3e95%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636886940307833288&sdata=GyQ%2Fwlf%2BzAeMYcNZZr21KhIFuYArXkhL2RSxJ1k3c7w%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABK16suGu9VCM0blflnB7r2q0mole-JSks5vYlmLgaJpZM4b_pqi&data=02%7C01%7Cmurasaki%40paho.org%7Ce82732dc7ae54911719c08d6ad4c3e95%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636886940307843296&sdata=diUnZVLF6vqSQ44vICgYeHoUsDEHEdq%2Bq4%2FgWuIB9nI%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
